[template]
cargo_generate_version = ">=0.9.0"
exclude = ["target/", "Cargo.lock", "rpm/icons"]

[placeholders]
org_domain = { type = "string", prompt = "Enter your reversed org domain (for example 'org.test')" }
description = { type = "string", prompt = "Description for the project?" }
license = { type = "string", prompt = "Which license do you want for this project?" }

[hooks]
pre = [
    "fix_assets_naming.rhai",
]
