import {
    VerticalBox,
    HorizontalBox,
    Button,
    Slider,
    SpinBox,
} from "std-widgets.slint";


export component AppWindow inherits Window {
    title: "Hello from slint";
    in-out property <length> font_size: 18px;
    VerticalBox {
        alignment: LayoutAlignment.stretch;

        // Отступ для статус бара
        Rectangle {
            width: 100%;
            height: 41px;
        }

        Text {
            text: "Hello from slint!";
            vertical-alignment: TextVerticalAlignment.center;
            horizontal-alignment: TextHorizontalAlignment.center;

            font-size: 18px * round(sin(180deg * animation-tick() / 1s));
        }
    }
}
